version: '3.8'
services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"  # Expose MySQL on the host
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Java Application Build & Run Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose the app on port 8080
    depends_on:
      - mysql  # Ensure MySQL is up before starting the app
    networks:
      - app-network

# Volume to persist MySQL data
volumes:
  mysql_data:

# Define a network for the app and MySQL to communicate
networks:
  app-network:
